ALTER TYPE "ImportSource" ADD VALUE IF NOT EXISTS 'IBKR_EMAIL_PDF';

ALTER TYPE "EmailScanRange" ADD VALUE IF NOT EXISTS 'SCAN_3D';

ALTER TYPE "EmailMessageStatus" ADD VALUE IF NOT EXISTS 'PARSED';
ALTER TYPE "EmailMessageStatus" ADD VALUE IF NOT EXISTS 'IMPORTED';
ALTER TYPE "EmailMessageStatus" ADD VALUE IF NOT EXISTS 'FAILED';
