ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'STOCK_GRANT';
ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'STOCK_DIVIDEND';
ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'TRANSFER_IN';
ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'TRANSFER_OUT';
ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'SPLIT';
ALTER TYPE "IbkrEventType" ADD VALUE IF NOT EXISTS 'REVERSE_SPLIT';

